services:
  loadbalancer:
    image: traefik:latest
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nginx:
    image: vietnguyen-nginx
    build:
      context: ./frontend/nginx
    depends_on:
      - loadbalancer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=82"
      - "traefik.http.routers.frontend.entrypoints=web"

  frontend:
    image: vietnguyen-frontend
    depends_on:
      - nginx
      - backend
    build:
      context: ./frontend
    environment:
      NODE_ENV: dev

  backend:
    image: vietnguyen-backend
    depends_on:
      - loadbalancer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=81"
      - "traefik.http.routers.backend.entrypoints=web"
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      NODE_ENV: dev
